### PR TITLE
Implemented save functionality Fix #8

### LINKED ISSUE #8: Implement save functionality
there should be autosave functionality, last valid state should be saved in localstorage, also it should be possible to share your work (maybe gist?) gist example https://gitlab.com/escherize/cljsfiddle/blob/master/src/cljs/cljsfiddle/gist.cljs

### PR DESCRIPTION
**Pull request by ghost**
Fixes #8 

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
thanks @poiga it works , but two moments
1) it should load state from localstorage on app init , and better to use this lib https://github.com/alandipert/storage-atom (transit version) much handy to work with LS
2) it should share link with our host and load this gist same as http://escherize.com/cljsfiddle/#gist=68f56bd279a0a3efbd3662c5e6a817e4 works

**Comment by flexsurfer** [comment]
so if we have gist in url we should load this gist, if not, load from localstorage, if localstorage is empty show our template

**Comment by audriu** [comment]
@flexsurfer I have fixed the save functionality! Hopes right this time!
P.S. I have changed my Github handle - not poiga any more :D

**Comment by flexsurfer** [comment]
thank you @audriu ! looks good ! :)

**Pull request merged**
