### PR TITLE
First draft.

### LINKED ISSUE #3: Implement parinfer editor and autocompile react native views
Implement similar functionality to http://escherize.com/cljsfiddle/, with the next differences 
1) page should be simpler - only two forms, code editor and a resulting view
2) compilation should be automatic (with error handling), no run button
3) code for parinfer editor should be as simple as possible with minimum assets
4) it should be possible to enter react-native-web components and see the result 

image

  **Edited**: please see comments to https://github.com/status-im/status-fiddle/pull/5

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3

Just wanted to show some progress.
Also criticism would be appreciated 

My aim is to make it as cool as in this web page [http://timothypratley.blogspot.lt/2017/01/reagent-deep-dive-part-2-lifecycle-of.html](url)  where you can edit even Reagent enabled code.

Next step would be to enable Parinfer editor.

status: wip

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @poiga , thanks , yeah i know about klipse, but we have different idea,
1 - parinfer editor should be fully under our control
2 - all code should be in our repo
thats why i gave that link, they have all the code we need in their repo, and we can use it, it's simple, we just need to remove extra functionality

The main idea of this project is rendering react native views, not code, just simple react native flex layout, it's for designers, so in parinfer editor should be code only for view as on my screenshot, nothing more, thanks

**Comment by ghost** [comment]
@flexsurfer so the only requirement is missing that it would render views (reagent and hiccup and DOM...). Then it will be ok?
And also we want that edit window input would be formatted and managed with the Parinfer formatter?

P.S. what did you mean 

> parinfer editor should be fully under our control

is it something related to library loading?

**Comment by flexsurfer** [comment]
sorry for the confusion, i didn't understand "where you can edit even Reagent enabled code."

parinfer editor should be fully under our control -  i meant we should compile the code by ourselves, so we should have editor in cljs code (cljs component) and watch changes and compile code and render resulting view, as it implemented here https://gitlab.com/escherize/cljsfiddle/blob/master/src/cljs/cljsfiddle/app.cljs#L100, but just add react-native-web ns support, tbh i think klipse is for just easy embed into html page, but we need cljs component in cljs project

**Comment by poiga** [comment]
@flexsurfer I like the comment from your code link: 

> ;; Fuck why does this work?

:rofl:

**Pull request closed without merging**
