### PR TITLE
fix simlink and fiddle url

### PR DESCRIPTION
**Pull request by gasolin**
found some small issues during build the repo.

Still got error while running `lein figwheel-repl`, but that is another issue.

```
Could not Analyze src/cljs/status_im/ui/components/list_selection.cljs
No such namespace: status-im.ui.components.react, could not locate status_im/ui/components/react.cljs, status_im/ui/components/react.cljc, or JavaScript source providing "status-im.ui.components.react" 
```

### CODE REVIEW

**Comment by flexsurfer** [comment]
thanks @gasolin . yeah this repo will not work with latest status-react. i'm working on this, will fix this week

**Comment by gasolin** [comment]
@flexsurfer do you have a working `status-react` commit hash# that I can try now?

**Comment by flexsurfer** [comment]
@gasolin i'm not sure but try this one https://github.com/status-im/status-react/commit/d692ddc7d9c80699eebead3a2434942fc59a0257

**Comment by gasolin** [comment]
@flexsurfer checkout status-react `d692ddc` works, thanks!

**Pull request merged**
