### PR TITLE
Implements all react-native components fixes #7

### LINKED ISSUE #7: Implement all react-native components

### PR DESCRIPTION
**Pull request by ghost**
F

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @audriu do you plan to work on this? because i need this asap, and will be working myself

**Comment by audriu** [comment]
Go on! I don't nave time for this at the moment...

**Comment by audriu** [comment]
I hope this one is still relevant

**Comment by flexsurfer** [comment]
@audriu i'll refactor status-react components next week, so this task is not relevant

**Pull request closed without merging**
