### PR TITLE
Second try #3. WIP

### LINKED ISSUE #3: Implement parinfer editor and autocompile react native views
Implement similar functionality to http://escherize.com/cljsfiddle/, with the next differences 
1) page should be simpler - only two forms, code editor and a resulting view
2) compilation should be automatic (with error handling), no run button
3) code for parinfer editor should be as simple as possible with minimum assets
4) it should be possible to enter react-native-web components and see the result 

image

  **Edited**: please see comments to https://github.com/status-im/status-fiddle/pull/5

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3 
status: wip

Just showing the progress. I need the your opinions
Going to refactor many things here.

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @poiga thanks for your effort, this is the right direction :) is it possible to decrease number of assets and files, do we really need all these js and css files?

**Comment by poiga** [comment]
Please try now. All should be good except styling of the divs.

**Comment by ghost** [comment]
@flexsurfer Please try now. All should be good except styling of the divs.

**Comment by flexsurfer** [comment]
thanks @poiga that's exactly what we need, let's just do something like
```clojure
(defn main-panel []
  [react/view {:style {:flex-direction :row :padding-vertical 50}}
   [react/view {:style {:flex 1 :padding-horizontal 50}}
    [code-mirror]]
   [react/view {:style {:flex 1 :padding-horizontal 50}}
    [dom-pane]]])
```

and we need two more things in this PR
1) errors handling, because now it crashes if enter something like
```clojure
[:h1 "Hello World!"
  []]
```

2) and `react-native-web` support, it should be possible to enter `react/view` in editor

Thanks!

**Comment by flexsurfer** [comment]
@poiga for 2 you just need to add `[status-fiddle.react-native-web :as react]`
```clojure
(str "(ns cljs.user
                    (:refer-clojure :exclude [atom])
                    (:require reagent.core [status-fiddle.react-native-web :as react]))

                  (def atom reagent.core/atom)"
                    (or (not-empty cljs-string)
                        "[:div]"))
```

**Comment by flexsurfer** [comment]
@poiga please share your thoughts about 1. errors handling, i think we could try on change before dispatch event , render first in some test div to do not crash our app, and if it rendered without errors we could dispatch event to render our reagent form, what do you think?

**Comment by ghost** [comment]
@flexsurfer  I am investigating this problem at the moment. I may try your approach as well.

**Comment by flexsurfer** [comment]
ok, thanks @poiga , no rush, just my thoughts, let's find better way

**Comment by poiga** [comment]
@flexsurfer I have a difficulty importing [hiccup.core :as hc] into views.cljs file even tho I have added the the dependency into project.clj file [hiccup "1.0.5"].
Any thoughts?

**Comment by ghost** [comment]
@flexsurfer I got an idea to use same assertions as Hiccup uses before rendering.

**Comment by ghost** [comment]
@flexsurfer please check now!

**Comment by flexsurfer** [comment]
@poiga can we render the previous valid view and show warning text under form? so the idea while you typing code we should see previous valid render and warning text if current code can't be rendered, thanks

**Comment by flexsurfer** [comment]
@poiga and also you forgot main thing :) initialize parinfer `(.init js/parinferCodeMirror cm)`

**Comment by flexsurfer** [comment]
@poiga still crashes if type something like `["test test"]` with space or `["test!"]`

**Comment by ghost** [comment]
@flexsurfer please check now!

**Comment by flexsurfer** [comment]
@poiga `react` ns doesn't work anymore, i mean `[react/view]` not valid because this `(not (keyword? (nth vec 0 nil))) false`

**Comment by ghost** [comment]
@flexsurfer please check now!

**Comment by flexsurfer** [comment]
thanks for your effort @poiga , i think we're done!

**Pull request merged**
